### ISSUE TITLE
Problema ao adicionar o package.json

### ISSUE THREAD

**Issue by LeandroDukievicz** [FrancoRoldao/Calculadora#1]
Franco, buenas 
Segui o passo a passo conforme o readme explica, e vejo no vs code, que aparece erro, e que não deixa os testes rodarem 

vou postar o código do jeito que fiz pra vc ver se eu fiz da maneira correta 

-----------------------
{
  "name": "teste-franco",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "cypress": "^9.5.1"
  }
  "scripts": {
   "cypress:open": "cypress open",
   "test": "cypress run"
 },
}
-------------------------------

eu fiz certo? se não me pontua o que ta errado pra eu tentar novamente por favor mano !

**Comment by FrancoRoldao** [comment]
Conforme conversamos anteriormente, o problema está no trecho "scripts", que deve existir somente 1, com o conteúdo informado no passo a passo. 
Abraços!
